//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayCollector.Business.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMedia
    {
        public long Id { get; set; }
        public long FK_Id_CollectionItem { get; set; }
        public string Name { get; set; }
        public string PathToFile { get; set; }
        public string Filename { get; set; }
        public string FileType { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual CollectionItem CollectionItem { get; set; }
    }
}
