//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayCollector.Business.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class playcollectorDb : DbContext
    {
        public playcollectorDb()
            : base("name=playcollectorDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CollectionItem> CollectionItemSet { get; set; }
        public virtual DbSet<Condition> ConditionSet { get; set; }
        public virtual DbSet<ItemMedia> ItemMediaSet { get; set; }
        public virtual DbSet<Storage> StorageSet { get; set; }
        public virtual DbSet<Theme> ThemeSet { get; set; }
    }
}
